#pragma once
#include "CoreMinimal.h"
#include "ESackboyAnimState.generated.h"

UENUM(BlueprintType)
enum class ESackboyAnimState : uint8 {
    Spawning,
    TetherSpawning,
    OnGround,
    Dying,
    Falling,
    Jumping,
    Slapping,
    Dazed,
    Cannon,
    Ledge_Grab,
    Swing,
    Emote,
    HitReaction,
    Grab,
    GrabConveyor,
    GrabDangle,
    GrabRocket,
    GrabSpinningWheel,
    RollRiding,
    Yanked,
    Carried,
    Thrown,
    Throw,
    Pickup,
    ThrowItem,
    Casting,
    Swinging,
    RangedPickup,
    Tugging,
    HeadBangerStun,
    Floating,
    VehicleRiding,
    PogoStick,
    AwaitingCopter,
    Umbrella,
    Unicycle,
    Snowball,
    Jetpack,
    GroundPound,
    AnimSequence,
    PodEntry,
    JumpToEnter,
    NumStates,
};

