#pragma once
#include "CoreMinimal.h"
#include "ESackboyAction.generated.h"

UENUM(BlueprintType)
enum class ESackboyAction : uint8 {
    Default,
    Spawning,
    Idling,
    Walking,
    Jumping,
    Falling,
    Dying,
    Jetpack,
    LedgeGrab,
    UTurn,
    Rolling,
    Sliding,
    Slap,
    TetherSpawning,
    Cannon,
    AwaitingRespawn,
    Yanked,
    Pickup,
    Throw,
    Carry,
    Carried,
    Thrown,
    Hidden,
    Emote,
    Grapple,
    HitReaction,
    Acting,
    DoubleTeam,
    RollRiding,
    CreativeBurst,
    ThrowItem,
    Diving,
    JumpToEnterLevelBadge,
    JumpToEnterObject,
    Vehicle,
    Snowball,
    Floating,
    Struggle,
    Cutscene,
    DropOut,
    AssistWait,
    HeadStomp,
    Grab,
    GrabConveyor,
    GrabDangle,
    GrabRocket,
    GrabSpinningWheel,
    GroundPound,
    Landing,
    AnimSequence,
    Limit,
};

